/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppProvider: typeof import('./src/components/app-provider/index.vue')['default']
    Content: typeof import('./src/components/layout/content.vue')['default']
    Footer: typeof import('./src/components/layout/footer.vue')['default']
    HeaderCenter: typeof import('./src/components/layout/header-center.vue')['default']
    HeaderLeft: typeof import('./src/components/layout/header-left.vue')['default']
    HeaderRight: typeof import('./src/components/layout/header-right.vue')['default']
    Layout: typeof import('./src/components/layout/index.vue')['default']
    LayoutPreference: typeof import('./src/components/preference-drawer/layout-preference.vue')['default']
    LoginIllustration: typeof import('./src/components/login-illustration.vue')['default']
    Logo: typeof import('./src/components/layout/logo.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    NCheckbox: typeof import('naive-ui')['NCheckbox']
    NColorPicker: typeof import('naive-ui')['NColorPicker']
    NDialogProvider: typeof import('naive-ui')['NDialogProvider']
    NDrawer: typeof import('naive-ui')['NDrawer']
    NDrawerContent: typeof import('naive-ui')['NDrawerContent']
    NFlex: typeof import('naive-ui')['NFlex']
    NForm: typeof import('naive-ui')['NForm']
    NFormItem: typeof import('naive-ui')['NFormItem']
    NIcon: typeof import('naive-ui')['NIcon']
    NInput: typeof import('naive-ui')['NInput']
    NInputNumber: typeof import('naive-ui')['NInputNumber']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NSelect: typeof import('naive-ui')['NSelect']
    NSwitch: typeof import('naive-ui')['NSwitch']
    NTabPane: typeof import('naive-ui')['NTabPane']
    NTabs: typeof import('naive-ui')['NTabs']
    PreferenceDrawer: typeof import('./src/components/preference-drawer/index.vue')['default']
    ProButton: typeof import('pro-naive-ui')['ProButton']
    ProCheckbox: typeof import('pro-naive-ui')['ProCheckbox']
    ProConfigProvider: typeof import('pro-naive-ui')['ProConfigProvider']
    ProForm: typeof import('pro-naive-ui')['ProForm']
    ProInput: typeof import('pro-naive-ui')['ProInput']
    ProLayout: typeof import('pro-naive-ui')['ProLayout']
    ProPassword: typeof import('pro-naive-ui')['ProPassword']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: typeof import('./src/components/layout/sidebar.vue')['default']
    SidebarExtra: typeof import('./src/components/layout/sidebar-extra.vue')['default']
    Tabbar: typeof import('./src/components/layout/tabbar.vue')['default']
    ThemePreference: typeof import('./src/components/preference-drawer/theme-preference.vue')['default']
  }
}
