/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppProvider: typeof import('./src/components/app-provider/index.vue')['default']
    Content: typeof import('./src/components/layout/content.vue')['default']
    Footer: typeof import('./src/components/layout/footer.vue')['default']
    HeaderCenter: typeof import('./src/components/layout/header-center.vue')['default']
    HeaderLeft: typeof import('./src/components/layout/header-left.vue')['default']
    HeaderRight: typeof import('./src/components/layout/header-right.vue')['default']
    Layout: typeof import('./src/components/layout/index.vue')['default']
    LayoutPreference: typeof import('./src/components/preference-drawer/layout-preference.vue')['default']
    Logo: typeof import('./src/components/layout/logo.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    NDialogProvider: typeof import('naive-ui')['NDialogProvider']
    NIcon: typeof import('naive-ui')['NIcon']
    NLoadingBarProvider: typeof import('naive-ui')['NLoadingBarProvider']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NModalProvider: typeof import('naive-ui')['NModalProvider']
    NNotificationProvider: typeof import('naive-ui')['NNotificationProvider']
    NSwitch: typeof import('naive-ui')['NSwitch']
    PreferenceDrawer: typeof import('./src/components/preference-drawer/index.vue')['default']
    ProButton: typeof import('pro-naive-ui')['ProButton']
    ProCheckbox: typeof import('pro-naive-ui')['ProCheckbox']
    ProConfigProvider: typeof import('pro-naive-ui')['ProConfigProvider']
    ProForm: typeof import('pro-naive-ui')['ProForm']
    ProInput: typeof import('pro-naive-ui')['ProInput']
    ProLayout: typeof import('pro-naive-ui')['ProLayout']
    ProPassword: typeof import('pro-naive-ui')['ProPassword']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: typeof import('./src/components/layout/sidebar.vue')['default']
    SidebarExtra: typeof import('./src/components/layout/sidebar-extra.vue')['default']
    Tabbar: typeof import('./src/components/layout/tabbar.vue')['default']
    ThemePreference: typeof import('./src/components/preference-drawer/theme-preference.vue')['default']
  }
}
