/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppProvider: typeof import('./src/components/app-provider/index.vue')['default']
    Footer: typeof import('./src/components/layout/footer.vue')['default']
    HeaderCenter: typeof import('./src/components/layout/header-center.vue')['default']
    HeaderLeft: typeof import('./src/components/layout/header-left.vue')['default']
    HeaderRight: typeof import('./src/components/layout/header-right.vue')['default']
    Layout: typeof import('./src/components/layout/index.vue')['default']
    LayoutMode: typeof import('./src/components/preference-drawer/layout-mode.vue')['default']
    LayoutPreference: typeof import('./src/components/preference-drawer/layout-preference.vue')['default']
    LayoutThumbnail: typeof import('./src/components/preference-drawer/layout-thumbnail.vue')['default']
    Logo: typeof import('./src/components/layout/logo.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    NColorPicker: typeof import('naive-ui')['NColorPicker']
    NDivider: typeof import('naive-ui')['NDivider']
    NDiviver: typeof import('naive-ui')['NDiviver']
    NDivver: typeof import('naive-ui')['NDivver']
    NDrawer: typeof import('naive-ui')['NDrawer']
    NDrawerContent: typeof import('naive-ui')['NDrawerContent']
    NDriver: typeof import('naive-ui')['NDriver']
    NFlex: typeof import('naive-ui')['NFlex']
    NGi: typeof import('naive-ui')['NGi']
    NGrid: typeof import('naive-ui')['NGrid']
    NIcon: typeof import('naive-ui')['NIcon']
    NInputNumber: typeof import('naive-ui')['NInputNumber']
    NList: typeof import('naive-ui')['NList']
    NListItem: typeof import('naive-ui')['NListItem']
    NSelect: typeof import('naive-ui')['NSelect']
    NSpace: typeof import('naive-ui')['NSpace']
    NSwitch: typeof import('naive-ui')['NSwitch']
    NTabPane: typeof import('naive-ui')['NTabPane']
    NTabs: typeof import('naive-ui')['NTabs']
    NTag: typeof import('naive-ui')['NTag']
    NThing: typeof import('naive-ui')['NThing']
    NTooltip: typeof import('naive-ui')['NTooltip']
    Preference: typeof import('./src/components/preference/index.vue')['default']
    PreferenceDrawer: typeof import('./src/components/preference-drawer/index.vue')['default']
    ProButton: typeof import('pro-naive-ui')['ProButton']
    ProCard: typeof import('pro-naive-ui')['ProCard']
    ProConfigProvider: typeof import('pro-naive-ui')['ProConfigProvider']
    ProLayout: typeof import('pro-naive-ui')['ProLayout']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: typeof import('./src/components/layout/sidebar.vue')['default']
    SidebarExtra: typeof import('./src/components/layout/sidebar-extra.vue')['default']
    Tabbar: typeof import('./src/components/layout/tabbar.vue')['default']
    Theme: typeof import('./src/components/preference-drawer/theme.vue')['default']
    ThemePreerence: typeof import('./src/components/preference-drawer/theme-preerence.vue')['default']
    ThemePreference: typeof import('./src/components/preference-drawer/theme-preference.vue')['default']
  }
}
