export { proIconifyIconsProps } from './props'
export { default as ProIconifyIcons } from './iconify-icons'
export { useIconifyIcons } from './composables/use-iconify-icons'
export type { ProIconifyIconsProps } from './props'
export type { ProIconifyIconsSlots } from './slots'
