export { createRouter } from './create-router'
export { linkPlugin } from './plugins/link-plugin'
export { nMenuPlugin } from './plugins/n-menu-plugin'
export { refreshPlugin } from './plugins/refresh-plugin'
export { progressPlugin } from './plugins/progress-plugin'
export { keepAlivePlugin } from './plugins/keep-alive-plugin'
export { transitionPlugin } from './plugins/transition-plugin'
export { breadcrumbPlugin } from './plugins/breadcrumb-plugin'
export { rbacAccessPlugin } from './plugins/rbac-access-plugin'
export { autoRedirectPlugin } from './plugins/auto-redirect-plugin'
export { documentTitlePlugin } from './plugins/document-title-plugin'
export { nestedRouteRenderPlugin } from './plugins/nested-route-render-plugin'
export { isEqualRoute, visitedRoutesPlugin } from './plugins/visited-routes-plugin'
export { getRouteComponentName } from './utils/route'
export * from './types'
